export interface IColScss {
  'col': string
  'span-1': string
  'span-2': string
  'span-3': string
  'span-4': string
  'span-5': string
  'span-6': string
  'span-7': string
  'span-8': string
  'span-9': string
  'span-10': string
  'span-11': string
  'span-12': string
  'span-13': string
  'span-14': string
  'span-15': string
  'span-16': string
  'span-17': string
  'span-18': string
  'span-19': string
  'span-20': string
  'span-21': string
  'span-22': string
  'span-23': string
  'span-24': string
  'span-xl-1': string
  'span-xl-2': string
  'span-xl-3': string
  'span-xl-4': string
  'span-xl-5': string
  'span-xl-6': string
  'span-xl-7': string
  'span-xl-8': string
  'span-xl-9': string
  'span-xl-10': string
  'span-xl-11': string
  'span-xl-12': string
  'span-xl-13': string
  'span-xl-14': string
  'span-xl-15': string
  'span-xl-16': string
  'span-xl-17': string
  'span-xl-18': string
  'span-xl-19': string
  'span-xl-20': string
  'span-xl-21': string
  'span-xl-22': string
  'span-xl-23': string
  'span-xl-24': string
  'span-lg-1': string
  'span-lg-2': string
  'span-lg-3': string
  'span-lg-4': string
  'span-lg-5': string
  'span-lg-6': string
  'span-lg-7': string
  'span-lg-8': string
  'span-lg-9': string
  'span-lg-10': string
  'span-lg-11': string
  'span-lg-12': string
  'span-lg-13': string
  'span-lg-14': string
  'span-lg-15': string
  'span-lg-16': string
  'span-lg-17': string
  'span-lg-18': string
  'span-lg-19': string
  'span-lg-20': string
  'span-lg-21': string
  'span-lg-22': string
  'span-lg-23': string
  'span-lg-24': string
  'span-md-1': string
  'span-md-2': string
  'span-md-3': string
  'span-md-4': string
  'span-md-5': string
  'span-md-6': string
  'span-md-7': string
  'span-md-8': string
  'span-md-9': string
  'span-md-10': string
  'span-md-11': string
  'span-md-12': string
  'span-md-13': string
  'span-md-14': string
  'span-md-15': string
  'span-md-16': string
  'span-md-17': string
  'span-md-18': string
  'span-md-19': string
  'span-md-20': string
  'span-md-21': string
  'span-md-22': string
  'span-md-23': string
  'span-md-24': string
  'span-sm-1': string
  'span-sm-2': string
  'span-sm-3': string
  'span-sm-4': string
  'span-sm-5': string
  'span-sm-6': string
  'span-sm-7': string
  'span-sm-8': string
  'span-sm-9': string
  'span-sm-10': string
  'span-sm-11': string
  'span-sm-12': string
  'span-sm-13': string
  'span-sm-14': string
  'span-sm-15': string
  'span-sm-16': string
  'span-sm-17': string
  'span-sm-18': string
  'span-sm-19': string
  'span-sm-20': string
  'span-sm-21': string
  'span-sm-22': string
  'span-sm-23': string
  'span-sm-24': string
  'span-xs-1': string
  'span-xs-2': string
  'span-xs-3': string
  'span-xs-4': string
  'span-xs-5': string
  'span-xs-6': string
  'span-xs-7': string
  'span-xs-8': string
  'span-xs-9': string
  'span-xs-10': string
  'span-xs-11': string
  'span-xs-12': string
  'span-xs-13': string
  'span-xs-14': string
  'span-xs-15': string
  'span-xs-16': string
  'span-xs-17': string
  'span-xs-18': string
  'span-xs-19': string
  'span-xs-20': string
  'span-xs-21': string
  'span-xs-22': string
  'span-xs-23': string
  'span-xs-24': string
  'offset-1': string
  'offset-2': string
  'offset-3': string
  'offset-4': string
  'offset-5': string
  'offset-6': string
  'offset-7': string
  'offset-8': string
  'offset-9': string
  'offset-10': string
  'offset-11': string
  'offset-12': string
  'offset-13': string
  'offset-14': string
  'offset-15': string
  'offset-16': string
  'offset-17': string
  'offset-18': string
  'offset-19': string
  'offset-20': string
  'offset-21': string
  'offset-22': string
  'offset-23': string
  'offset-24': string
  'offset-xl-1': string
  'offset-xl-2': string
  'offset-xl-3': string
  'offset-xl-4': string
  'offset-xl-5': string
  'offset-xl-6': string
  'offset-xl-7': string
  'offset-xl-8': string
  'offset-xl-9': string
  'offset-xl-10': string
  'offset-xl-11': string
  'offset-xl-12': string
  'offset-xl-13': string
  'offset-xl-14': string
  'offset-xl-15': string
  'offset-xl-16': string
  'offset-xl-17': string
  'offset-xl-18': string
  'offset-xl-19': string
  'offset-xl-20': string
  'offset-xl-21': string
  'offset-xl-22': string
  'offset-xl-23': string
  'offset-xl-24': string
  'offset-lg-1': string
  'offset-lg-2': string
  'offset-lg-3': string
  'offset-lg-4': string
  'offset-lg-5': string
  'offset-lg-6': string
  'offset-lg-7': string
  'offset-lg-8': string
  'offset-lg-9': string
  'offset-lg-10': string
  'offset-lg-11': string
  'offset-lg-12': string
  'offset-lg-13': string
  'offset-lg-14': string
  'offset-lg-15': string
  'offset-lg-16': string
  'offset-lg-17': string
  'offset-lg-18': string
  'offset-lg-19': string
  'offset-lg-20': string
  'offset-lg-21': string
  'offset-lg-22': string
  'offset-lg-23': string
  'offset-lg-24': string
  'offset-md-1': string
  'offset-md-2': string
  'offset-md-3': string
  'offset-md-4': string
  'offset-md-5': string
  'offset-md-6': string
  'offset-md-7': string
  'offset-md-8': string
  'offset-md-9': string
  'offset-md-10': string
  'offset-md-11': string
  'offset-md-12': string
  'offset-md-13': string
  'offset-md-14': string
  'offset-md-15': string
  'offset-md-16': string
  'offset-md-17': string
  'offset-md-18': string
  'offset-md-19': string
  'offset-md-20': string
  'offset-md-21': string
  'offset-md-22': string
  'offset-md-23': string
  'offset-md-24': string
  'offset-sm-1': string
  'offset-sm-2': string
  'offset-sm-3': string
  'offset-sm-4': string
  'offset-sm-5': string
  'offset-sm-6': string
  'offset-sm-7': string
  'offset-sm-8': string
  'offset-sm-9': string
  'offset-sm-10': string
  'offset-sm-11': string
  'offset-sm-12': string
  'offset-sm-13': string
  'offset-sm-14': string
  'offset-sm-15': string
  'offset-sm-16': string
  'offset-sm-17': string
  'offset-sm-18': string
  'offset-sm-19': string
  'offset-sm-20': string
  'offset-sm-21': string
  'offset-sm-22': string
  'offset-sm-23': string
  'offset-sm-24': string
  'offset-xs-1': string
  'offset-xs-2': string
  'offset-xs-3': string
  'offset-xs-4': string
  'offset-xs-5': string
  'offset-xs-6': string
  'offset-xs-7': string
  'offset-xs-8': string
  'offset-xs-9': string
  'offset-xs-10': string
  'offset-xs-11': string
  'offset-xs-12': string
  'offset-xs-13': string
  'offset-xs-14': string
  'offset-xs-15': string
  'offset-xs-16': string
  'offset-xs-17': string
  'offset-xs-18': string
  'offset-xs-19': string
  'offset-xs-20': string
  'offset-xs-21': string
  'offset-xs-22': string
  'offset-xs-23': string
  'offset-xs-24': string
  'order-1': string
  'order-2': string
  'order-3': string
  'order-4': string
  'order-5': string
  'order-6': string
  'order-7': string
  'order-8': string
  'order-9': string
  'order-10': string
  'order-11': string
  'order-12': string
  'order-13': string
  'order-14': string
  'order-15': string
  'order-16': string
  'order-17': string
  'order-18': string
  'order-19': string
  'order-20': string
  'order-21': string
  'order-22': string
  'order-23': string
  'order-24': string
  'order-xl-1': string
  'order-xl-2': string
  'order-xl-3': string
  'order-xl-4': string
  'order-xl-5': string
  'order-xl-6': string
  'order-xl-7': string
  'order-xl-8': string
  'order-xl-9': string
  'order-xl-10': string
  'order-xl-11': string
  'order-xl-12': string
  'order-xl-13': string
  'order-xl-14': string
  'order-xl-15': string
  'order-xl-16': string
  'order-xl-17': string
  'order-xl-18': string
  'order-xl-19': string
  'order-xl-20': string
  'order-xl-21': string
  'order-xl-22': string
  'order-xl-23': string
  'order-xl-24': string
  'order-lg-1': string
  'order-lg-2': string
  'order-lg-3': string
  'order-lg-4': string
  'order-lg-5': string
  'order-lg-6': string
  'order-lg-7': string
  'order-lg-8': string
  'order-lg-9': string
  'order-lg-10': string
  'order-lg-11': string
  'order-lg-12': string
  'order-lg-13': string
  'order-lg-14': string
  'order-lg-15': string
  'order-lg-16': string
  'order-lg-17': string
  'order-lg-18': string
  'order-lg-19': string
  'order-lg-20': string
  'order-lg-21': string
  'order-lg-22': string
  'order-lg-23': string
  'order-lg-24': string
  'order-md-1': string
  'order-md-2': string
  'order-md-3': string
  'order-md-4': string
  'order-md-5': string
  'order-md-6': string
  'order-md-7': string
  'order-md-8': string
  'order-md-9': string
  'order-md-10': string
  'order-md-11': string
  'order-md-12': string
  'order-md-13': string
  'order-md-14': string
  'order-md-15': string
  'order-md-16': string
  'order-md-17': string
  'order-md-18': string
  'order-md-19': string
  'order-md-20': string
  'order-md-21': string
  'order-md-22': string
  'order-md-23': string
  'order-md-24': string
  'order-sm-1': string
  'order-sm-2': string
  'order-sm-3': string
  'order-sm-4': string
  'order-sm-5': string
  'order-sm-6': string
  'order-sm-7': string
  'order-sm-8': string
  'order-sm-9': string
  'order-sm-10': string
  'order-sm-11': string
  'order-sm-12': string
  'order-sm-13': string
  'order-sm-14': string
  'order-sm-15': string
  'order-sm-16': string
  'order-sm-17': string
  'order-sm-18': string
  'order-sm-19': string
  'order-sm-20': string
  'order-sm-21': string
  'order-sm-22': string
  'order-sm-23': string
  'order-sm-24': string
  'order-xs-1': string
  'order-xs-2': string
  'order-xs-3': string
  'order-xs-4': string
  'order-xs-5': string
  'order-xs-6': string
  'order-xs-7': string
  'order-xs-8': string
  'order-xs-9': string
  'order-xs-10': string
  'order-xs-11': string
  'order-xs-12': string
  'order-xs-13': string
  'order-xs-14': string
  'order-xs-15': string
  'order-xs-16': string
  'order-xs-17': string
  'order-xs-18': string
  'order-xs-19': string
  'order-xs-20': string
  'order-xs-21': string
  'order-xs-22': string
  'order-xs-23': string
  'order-xs-24': string
}
declare const styles: IColScss;
export default styles;
